# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    url "https://github.com/akokubu/hello-cli/releases/download/v0.2.0/hello-cli_Darwin_x86_64.tar.gz"
    sha256 "ac85c7611100b0f2967deb954d4ae1637589165847bccb9c3be0ed2c8e0d0084"

    def install
      bin.install "hello-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the HelloCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/akokubu/hello-cli/releases/download/v0.2.0/hello-cli_Linux_x86_64.tar.gz"
      sha256 "d13f83001fe1184c37c7612b623b2a9be3b6e1396f2126dcbe238e14466bb941"

      def install
        bin.install "hello-cli"
      end
    end
  end
end
